baseURL = "https://150ans.lalib.ch"
languageCode = "fr-ch"
title = "La Liberté a 150 ans"
theme = "laliberte"

[params]
  timelineTitle = "La timeline de la Liberté"
  circulateNavigationTitle = 'Poursuivre la lecture'
  aboutPageTitle = 'À propos'
  aboutPageSlug = 'a-propos'
  videoActionLabel = 'Voir le reportage'
  footerRight = "Tous droits réservés"
  Plausible = '150.lalib.ch'

[markup]
  [markup.goldmark]
	[markup.goldmark.renderer]
	  unsafe = true