baseURL = "https://150ans.lalib.ch"
languageCode = "fr-ch"
title = "150 ans de Liberté"
theme = "laliberte"

[params]
  timelineTitle = "150 ans de Liberté"
  circulateNavigationTitle = 'Poursuivre la lecture'
  aboutPageTitle = 'À propos'
  aboutPageSlug = 'a-propos'
  videoActionLabel = 'Voir le reportage'
  footerRight = "Tous droits réservés"
  Plausible = '150ans.lalib.ch'

[markup]
  [markup.goldmark]
	[markup.goldmark.renderer]
	  unsafe = true