baseURL = "https://laliberte150.staging.antistatique.net/"
languageCode = "fr-ch"
title = "La Liberté a 150 ans"
theme = "laliberte"


[markup]
  [markup.goldmark]
	[markup.goldmark.renderer]
	  unsafe = true