baseURL = "https://laliberte150.staging.antistatique.net/"
languageCode = "fr-ch"
title = "La Liberté a 150 ans"
theme = "laliberte"

[params]
  circulateNavigationTitle = 'Poursuivre la lecture'
  aboutPageTitle = 'À propos'
  aboutPageSlug = 'a-propos'

[markup]
  [markup.goldmark]
	[markup.goldmark.renderer]
	  unsafe = true