name: Deploy FTP
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with: null
        hugo-version: 0.80.0
      - name: Build
        run: hugo --minify
      - name: FTP Deploy
uses: SamKirkland/FTP-Deploy-Action@3.0.0
with: null
ftp-server: '${{ secrets.FTP_HOST }}'
ftp-username: '${{ secrets.FTP_USERNAME }}'
ftp-password: '${{ secrets.FTP_PASSWORD }}'
local-dir: public/
server-dir: www/
